# Generated by Django 5.1.1 on 2024-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='Текст сообщения')),
                ('duration', models.IntegerField(verbose_name='Длительность видео в секундах')),
                ('width', models.IntegerField(verbose_name='Ширина видео')),
                ('height', models.IntegerField(verbose_name='Длина видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file_name', models.CharField(max_length=100, verbose_name='Название файла видео')),
            ],
        ),
    ]
